set PATH=%PATH%;H:\SRC;H:\DEVKIT\BIN
set RDBRC=H:\DEVKIT\BIN\RDB.RC
set DBPATH=H:\DEVKIT\BIN
set ALNPATH=H:\DEVKIT\BIN
set MACPATH=H:\DEVKIT\INCLUDE
set GCC_EXEC_PREFIX=H:/DEVKIT/BIN
set TEMP=H: