@echo off
cls
set PATH=%PATH%;C:\JAGUAR\SRC;C:\JAGUAR\DEVKIT\BIN
set INCLUDE=C:\JAGUAR\DEVKIT\INCLUDE;C:\JAGUAR\DEVKIT\LIB\3D\INCLUDE;%INCLUDE%
set LIBRARY_PATH=C:\JAGUAR\DEVKIT\LIB;C:\JAGUAR\DEVKIT\LIB\3D;%LIBRARY_PATH%
set RDBRC=C:\JAGUAR\DEVKIT\BIN\RDB.RC
set DBPATH=C:\JAGUAR\DEVKIT\BIN
set ALNPATH=C:\JAGUAR\DEVKIT\BIN
set MACPATH=C:\JAGUAR\DEVKIT\INCLUDE
set GCC_EXEC_PREFIX=C:/JAGUAR/DEVKIT/BIN/
set TEMP=C:\JAGUAR\Temp
cd C:\JAGUAR\SRC
@echo.
@echo Paths Set!
